- - FILLER1
  - 8
- - DOB_YY
  - 4
- - DOB_MM
  - 2
- - FILLER2
  - 4
- - DOB_TT
  - 4
- - DOB_WK
  - 1
- - FILLER3
  - 8
- - BFACIL
  - 1
- - F_FACILITY
  - 1
- - FILLER4
  - 16
- - BFACIL3
  - 1
- - FILLER5
  - 22
- - MAGE_IMPFLG
  - 1
- - MAGE_REPFLG
  - 1
- - MAGER
  - 2
- - MAGER14
  - 2
- - MAGER9
  - 1
- - FILLER6
  - 4
- - MBSTATE_REC
  - 1
- - FILLER7
  - 19
- - RESTATUS
  - 1
- - MRACE31
  - 2
- - MRACE6
  - 1
- - MRACE15
  - 2
- - MBRACE
  - 1
- - MRACEIMP
  - 1
- - MHISPX
  - 1
- - FILLER8
  - 2
- - MHISP_R
  - 1
- - F_MHISP
  - 1
- - MRACEHISP
  - 1
- - FILLER9
  - 1
- - MAR_P
  - 1
- - DMAR
  - 1
- - MAR_IMP
  - 1
- - FILLER10
  - 1
- - F_MAR_P
  - 1
- - MEDUC
  - 1
- - FILLER11
  - 1
- - F_MEDUC
  - 1
- - FILLER12
  - 15
- - FAGERPT_FLG
  - 1
- - FILLER13
  - 4
- - FAGECOMB
  - 2
- - FAGEREC11
  - 2
- - FRACE31
  - 2
- - FRACE6
  - 1
- - FRACE15
  - 2
- - FILLER
  - 3
- - FHISPX
  - 1
- - FHISP_R
  - 1
- - F_HISP
  - 1
- - FRACEHISP
  - 1
- - FEDUC
  - 1
- - FILLER14
  - 1
- - F_FEDUC
  - 1
- - FILLER15
  - 5
- - PRIORLIVE
  - 2
- - PRIORDEAD
  - 2
- - PRIORTERM
  - 2
- - FILLER16
  - 2
- - LBO_REC
  - 1
- - FILLER17
  - 2
- - TBO_REC
  - 1
- - FILLER18
  - 15
- - ILLB_R
  - 3
- - ILLB_R11
  - 2
- - FILLER19
  - 3
- - ILOP_R
  - 3
- - ILOP_R11
  - 2
- - FILLER20
  - 3
- - ILP_R
  - 3
- - ILP_R11
  - 2
- - FILLER21
  - 5
- - PRECARE
  - 2
- - F_MPCB
  - 1
- - PRECARE5
  - 1
- - FILLER22
  - 10
- - PREVIS
  - 2
- - FILLER23
  - 2
- - PREVIS_REC
  - 2
- - F_TPCV
  - 1
- - FILLER24
  - 6
- - WIC
  - 1
- - F_WIC
  - 1
- - CIG_0
  - 2
- - CIG_1
  - 2
- - CIG_2
  - 2
- - CIG_3
  - 2
- - CIG0_R
  - 1
- - CIG1_R
  - 1
- - CIG2_R
  - 1
- - CIG3_R
  - 1
- - F_CIGS_0
  - 1
- - F_CIGS_1
  - 1
- - F_CIGS_2
  - 1
- - F_CIGS_3
  - 1
- - CIG_REC
  - 1
- - F_TOBACCO
  - 1
- - FILLER25
  - 9
- - M_HT_IN
  - 2
- - F_M_HT
  - 1
- - BMI
  - 4
- - BMI_R
  - 1
- - FILLER26
  - 4
- - PWGT_R
  - 3
- - F_PWGT
  - 1
- - FILLER27
  - 3
- - DWGT_R
  - 3
- - FILLER28
  - 1
- - F_DWGT
  - 1
- - WTGAIN
  - 2
- - WTGAIN_REC
  - 1
- - F_WTGAIN
  - 1
- - FILLER29
  - 5
- - RF_PDIAB
  - 1
- - RF_GDIAB
  - 1
- - RF_PHYPE
  - 1
- - RF_GHYPE
  - 1
- - RF_EHYPE
  - 1
- - RF_PPTERM
  - 1
- - F_RF_PDIAB
  - 1
- - F_RF_GDIAB
  - 1
- - F_RF_PHYPER
  - 1
- - F_RF_GHYPER
  - 1
- - F_RF_ECLAMP
  - 1
- - F_RF_PPB
  - 1
- - RF_INFTR
  - 1
- - RF_FEDRG
  - 1
- - RF_ARTEC
  - 1
- - F_RF_INFT
  - 1
- - F_RF_INF_DRG
  - 1
- - F_RF_INF_ART
  - 1
- - RF_CESAR
  - 1
- - RF_CESARN
  - 2
- - FILLER30
  - 1
- - F_RF_CESAR
  - 1
- - F_RF_NCESAR
  - 1
- - NO_RISKS
  - 1
- - FILLER31
  - 5
- - IP_GON
  - 1
- - IP_SYPH
  - 1
- - IP_CHLAM
  - 1
- - IP_HEPB
  - 1
- - IP_HEPC
  - 1
- - F_IP_GONOR
  - 1
- - F_IP_SYPH
  - 1
- - F_IP_CHLAM
  - 1
- - F_IP_HEPATB
  - 1
- - F_IP_HEPATC
  - 1
- - NO_INFEC
  - 1
- - FILLER32
  - 6
- - OB_ECVS
  - 1
- - OB_ECVF
  - 1
- - FILLER33
  - 1
- - F_OB_SUCC
  - 1
- - F_OB_FAIL
  - 1
- - FILLER34
  - 18
- - LD_INDL
  - 1
- - LD_AUGM
  - 1
- - LD_STER
  - 1
- - LD_ANTB
  - 1
- - LD_CHOR
  - 1
- - LD_ANES
  - 1
- - F_LD_INDL
  - 1
- - F_LD_AUGM
  - 1
- - F_LD_STER
  - 1
- - F_LD_ANTB
  - 1
- - F_LD_CHOR
  - 1
- - F_LD_ANES
  - 1
- - NO_LBRDLV
  - 1
- - FILLER35
  - 5
- - ME_PRES
  - 1
- - ME_ROUT
  - 1
- - ME_TRIAL
  - 1
- - F_ME_PRES
  - 1
- - F_ME_ROUT
  - 1
- - F_ME_TRIAL
  - 1
- - RDMETH_REC
  - 1
- - DMETH_REC
  - 1
- - F_DMETH_REC
  - 1
- - FILLER36
  - 5
- - MM_MTR
  - 1
- - MM_PLAC
  - 1
- - MM_RUPT
  - 1
- - MM_UHYST
  - 1
- - MM_AICU
  - 1
- - FILLER37
  - 1
- - F_MM_MTR
  - 1
- - F_MM_PLAC
  - 1
- - F_MM_RUPT
  - 1
- - F_MM_UHYST
  - 1
- - F_MM_AICU
  - 1
- - FILLER38
  - 1
- - NO_MMORB
  - 1
- - FILLER39
  - 5
- - ATTEND
  - 1
- - MTRAN
  - 1
- - PAY
  - 1
- - PAY_REC
  - 1
- - F_PAY
  - 1
- - F_PAY_REC
  - 1
- - FILLER40
  - 5
- - APGAR5
  - 2
- - APGAR5R
  - 1
- - F_APGAR5
  - 1
- - APGAR10
  - 2
- - APGAR10R
  - 1
- - FILLER41
  - 3
- - DPLURAL
  - 1
- - FILLER42
  - 1
- - IMP_PLUR
  - 1
- - FILLER43
  - 2
- - SETORDER_R
  - 1
- - FILLER44
  - 15
- - SEX
  - 1
- - IMP_SEX
  - 1
- - DLMP_MM
  - 2
- - FILLER45
  - 2
- - DLMP_YY
  - 4
- - FILLER46
  - 3
- - COMPGST_IMP
  - 1
- - OBGEST_FLG
  - 1
- - COMBGEST
  - 2
- - GESTREC10
  - 2
- - GESTREC3
  - 1
- - FILLER47
  - 3
- - LMPUSED
  - 1
- - OEGEST_COMB
  - 2
- - OEGEST_R10
  - 2
- - OEGEST_R3
  - 1
- - DBWT
  - 4
- - FILLER48
  - 1
- - BWTR12
  - 2
- - BWTR4
  - 1
- - FILLER49
  - 5
- - AB_AVEN1
  - 1
- - AB_AVEN6
  - 1
- - AB_NICU
  - 1
- - AB_SURF
  - 1
- - AB_ANTI
  - 1
- - AB_SEIZ
  - 1
- - FILLER50
  - 1
- - F_AB_VENT
  - 1
- - F_AB_VENT6
  - 1
- - F_AB_NICU
  - 1
- - F_AB_SURFAC
  - 1
- - F_AB_ANTIBIO
  - 1
- - F_AB_SEIZ
  - 1
- - FILLER51
  - 1
- - NO_ABNORM
  - 1
- - FILLER52
  - 5
- - CA_ANEN
  - 1
- - CA_MNSB
  - 1
- - CA_CCHD
  - 1
- - CA_CDH
  - 1
- - CA_OMPH
  - 1
- - CA_GAST
  - 1
- - F_CA_ANEN
  - 1
- - F_CA_MENIN
  - 1
- - F_CA_HEART
  - 1
- - F_CA_HERNIA
  - 1
- - F_CA_OMPHA
  - 1
- - F_CA_GASTRO
  - 1
- - CA_LIMB
  - 1
- - CA_CLEFT
  - 1
- - CA_CLPAL
  - 1
- - CA_DOWN
  - 1
- - CA_DISOR
  - 1
- - CA_HYPO
  - 1
- - F_CA_LIMB
  - 1
- - F_CA_CLEFTLP
  - 1
- - F_CA_CLEFT
  - 1
- - F_CA_DOWNS
  - 1
- - F_CA_CHROM
  - 1
- - F_CA_HYPOS
  - 1
- - NO_CONGEN
  - 1
- - FILLER53
  - 5
- - ITRAN
  - 1
- - ILIV
  - 1
- - BFED
  - 1
- - F_BFED
  - 1
- - FILLER54
  - 760
